#!/bin/bash
set -ev

# Configuration.
export COLCON_WS=~/ws
export COLCON_WS_SRC=${COLCON_WS}/src
export DEBIAN_FRONTEND=noninteractive

# Dependencies.
echo "deb [trusted=yes] http://packages.osrfoundation.org/gazebo/ubuntu-stable bionic main" > /etc/apt/sources.list.d/gazebo-stable.list
echo "deb [trusted=yes] http://packages.ros.org/ros2/ubuntu bionic main" > /etc/apt/sources.list.d/ros2-latest.list
apt-get update -qq
apt-get install -qq -y \
  libgazebo9-dev \
  ignition-citadel \
  python3-colcon-common-extensions \
  python-rosdep \
  git

# Get ros_ign
mkdir -p $COLCON_WS_SRC
cd $COLCON_WS_SRC
git clone https://github.com/ignitionrobotics/ros_ign -b dashing

# Install dependencies
cd $COLCON_WS
rosdep init
rosdep update
rosdep install --from-paths src -i -y --rosdistro eloquent \
  --skip-keys=ignition-math6 \
  --skip-keys=ignition-msgs5 \
  --skip-keys=ignition-transport8 \
  --skip-keys=ignition-gazebo3

# Build
source /opt/ros/eloquent/setup.bash
ln -s /code $COLCON_WS_SRC
cd $COLCON_WS
colcon build

# Tests
colcon test
colcon test-result
