#!/bin/bash
set -ev

# Configuration.
export COLCON_WS=~/ws
export COLCON_WS_SRC=${COLCON_WS}/src
export DEBIAN_FRONTEND=noninteractive

# Dependencies.
echo "deb [trusted=yes] http://packages.osrfoundation.org/gazebo/ubuntu-stable bionic main" > /etc/apt/sources.list.d/gazebo-stable.list
echo "deb [trusted=yes] http://packages.ros.org/ros2/ubuntu bionic main" > /etc/apt/sources.list.d/ros2-latest.list
apt-get update -qq
apt-get install -qq -y libgazebo9-dev \
                       python3-colcon-common-extensions \
                       python-rosdep

rosdep init
rosdep update
rosdep install --from-paths ./ -i -y --rosdistro eloquent

# Build.
source /opt/ros/eloquent/setup.bash
mkdir -p $COLCON_WS_SRC
ln -s /code $COLCON_WS_SRC
cd $COLCON_WS
colcon build

# Tests.
colcon test

