#!/bin/bash
set -ev

# Configuration
export COLCON_WS=~/ws
export COLCON_WS_SRC=${COLCON_WS}/src
export DEBIAN_FRONTEND=noninteractive

# Install system dependencies
apt-get update -qq
apt-get install -qq -y \
  curl \
  git \
  gnupg2 \
  lsb-release
curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -

echo "deb [arch=$(dpkg --print-architecture)] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" > /etc/apt/sources.list.d/ros2-latest.list

apt-get update -qq
apt-get install -qq -y \
  python3-colcon-common-extensions \
  python3-rosdep

# Get ros_ign (TODO: remove once released upstream)
mkdir -p $COLCON_WS_SRC
ln -s /code $COLCON_WS_SRC
cd $COLCON_WS_SRC
git clone https://github.com/ignitionrobotics/ros_ign -b ros2

# Install ROS, Gazebo and Ignition
cd $COLCON_WS
rosdep init
rosdep update
rosdep install --from-paths src -i -y --rosdistro foxy

# Build
source /opt/ros/foxy/setup.bash
cd $COLCON_WS
colcon build

# Tests
colcon test --packages-select-regex dolly
colcon test-result
